/**
 * Persists the server-side portfolio transforms to disk.
 *
 * - Rewrites the captured page shells (en/*.html, templates/project.html) with
 *   the current portfolio content, SEO metadata and payloads.
 * - Rewrites the _nuxt chunks with the local-content patches.
 * - Emits page-data.js, the payload data the app uses on client-side
 *   navigation instead of a CMS.
 *
 * Safe to run repeatedly: every transform is positional and idempotent.
 */
const fs = require('fs');
const path = require('path');
const server = require('../server');
const PORTFOLIO_CONTENT = require('../portfolio-content');

const ROOT = server.ROOT;
const BASE_URL = process.env.BASE_URL || 'http://127.0.0.1:4173';
const firstProject = PORTFOLIO_CONTENT.work.en.cases[0];

const pages = [
  ...Object.entries(server.PAGE_FILES).map(([pathname, file]) => ({ pathname, file })),
  { pathname: `/work/${firstProject.slug}`, file: server.PROJECT_TEMPLATE, key: 'project' }
];

const pageData = {};

for (const page of pages) {
  const source = fs.readFileSync(page.file, 'utf8');
  const html = server.transformHtml(source, page.pathname, `${BASE_URL}${page.pathname}`);
  fs.writeFileSync(page.file, html, 'utf8');

  const parsed = server.parseNuxtPayload(html, page.pathname);
  const entry = parsed && Array.isArray(parsed.payload.data)
    ? parsed.payload.data.find((item) => item && item.data)
    : null;
  const key = page.key || (page.pathname === '/' ? 'home' : page.pathname.slice(1));
  pageData[key] = entry ? entry.data : {};
  console.log(`baked ${path.relative(ROOT, page.file)} (${page.pathname})`);
}

const nuxtDirectory = path.join(ROOT, '_nuxt');
for (const fileName of fs.readdirSync(nuxtDirectory)) {
  if (!fileName.endsWith('.js')) continue;
  const filePath = path.join(nuxtDirectory, fileName);
  const source = fs.readFileSync(filePath, 'utf8');
  const patched = server.transformNuxtScript(source, fileName);
  if (patched !== source) {
    fs.writeFileSync(filePath, patched, 'utf8');
    console.log(`patched _nuxt/${fileName}`);
  }
}

const pageDataSource =
  `// Generated by scripts/bake.js — payload data served to the app on client-side navigation.\n` +
  `window.__TIANLU_PAGE_DATA__ = ${JSON.stringify(pageData).replaceAll('<', '\\u003c')};\n`;
fs.writeFileSync(path.join(ROOT, 'page-data.js'), pageDataSource, 'utf8');
console.log('wrote page-data.js');
